Vagrant.configure("2") do |config|

  config.vm.define "windows10" do |win10|
    win10.vm.box = "gusztavvargadr/windows-10"
    win10.vm.provision "shell", path:"../windows-scripts/setupWinX.ps1"
  
    win10.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "8192"
    end

  end
  
end